version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /bl3auto
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /cloudflared
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /coredns
    schedule:
      interval: "daily"
      
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /dnscontrol
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /dnscrypt-proxy
    schedule:
      interval: "daily"
      
   # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /lego
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /youtube-dl
    schedule:
      interval: "daily"

