name: bl3auto

on:
  push:
    branches: 
      - main
    paths:
      - bl3auto/*
      - .github/workflows/bl3auto.yml
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

env:
  BUILD_VERSION: "v2.2"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }} 

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4 
 
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: "https://github.com/docker/buildx.git#67bd6f4dc82a9cd96f34133dab3f6f7af803bb14"
          driver-opts: image=moby/buildkit:master
          buildkitd-flags: --debug

      - name: Set Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }}
          labels: |
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=${{ env.REPOSITORY }}

      - name: GitHub login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: DockerHub login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      

      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ${{ github.workflow }}
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          build-args: BUILD_VERSION
          cache-from: type=gha
          cache-to: type=gha
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            docker.io/${{ env.REPOSITORY }}:latest
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            ghcr.io/${{ env.REPOSITORY }}:latest
