name: dnscrypt-proxy

on:
  push:
    branches: 
      - main
    paths:
      - dnscrypt-proxy
      - .github/workflows/dnscrypt-proxy.yml

env:
  BUILD_VERSION: "2.0.45"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: jauderho/dnscrypt-proxy

jobs:
  login:
    runs-on: ${{ matrix.OS }}
    
    strategy:
      matrix:
        PLATFORM: [linux/amd64,linux/386]
        OS: [ubuntu-latest]
    
    steps:
      - name: github login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "${GITHUB_ACTOR}"
          password: ${{ secrets.CR_PAT }}

      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      
     
