name: dnscrypt-proxy

on:
  push:
    branches: 
      - main
    paths:
      - dnscrypt-proxy
      - .github/workflows/dnscrypt-proxy.yml

env:
  BUILD_VERSION: "2.0.45"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: jauderho/dnscrypt-proxy

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: GitHub login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{ secrets.CR_PAT }}

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      
 
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
 
      - name: Build
        run: >-
            docker buildx build "${GITHUB_WORKFLOW}" --pull --push
            --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/arm/v6
            --build-arg BUILD_VERSION
            --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            --label "org.opencontainers.image.version=${BUILD_VERSION}"
            --label "org.opencontainers.image.revision=$(git describe --tags --always --dirty)"
            --tag docker.io/${REPOSITORY}:${BUILD_VERSION}
            --tag docker.io/${REPOSITORY}:latest
            --tag ghcr.io/${REPOSITORY}:${BUILD_VERSION}
            --tag ghcr.io/${REPOSITORY}:latest
