name: dnscrypt-proxy-docs

on:
  push:
    branches: 
      - main
    paths:
      - README.md
      - dnscrypt-proxy/
      - .github/workflows/dnscrypt-proxy-docs.yml

env:
  BUILD_VERSION: "2.0.45"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: jauderho/dnscrypt-proxy

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: dockerhub description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${REPOSITORY}
