#
# Disabled for now due to the inability to pass tokens instead of passwords to Docker Hub
#
name: dnscrypt-proxy-docs

on:
  push:
    branches: 
      - main
    paths:
      - README.md
      - dnscrypt-proxy
      - .github/workflows/dnscrypt-proxy.yml
      - .github/workflows/dnscrypt-proxy-docs.yml

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/dnscrypt-proxy

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0 
        
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.REPOSITORY }}
          readme-filepath: dnscrypt-proxy/README.md
