#
# Disabled for now due to the inability to pass tokens instead of passwords to Docker Hub
#
name: dnscrypt-proxy-docs

on:
  push:
    branches: 
      - main
    paths:
      - README.md
      - dnscrypt-proxy
      - .github/workflows/dnscrypt-proxy.yml
      - .github/workflows/dnscrypt-proxy-docs.yml

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/dnscrypt-proxy

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      packages: write

    steps:
      - name: Source checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@616d1b63e806b630b975af3b4fe3304307b20f40 # v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.REPOSITORY }}
          readme-filepath: dnscrypt-proxy/README.md
