name: dnscrypt-proxy

on:
  push:
    branches: 
      - main
    paths:
      - dnscrypt-proxy
      - .github/workflows/dnscrypt-proxy.yml

env:
  BUILD_VERSION: "2.0.45"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }} 

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: GitHub login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      
 
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
 
      - name: Show commit SHA
        run: echo ${{ github.sha }}
        
      - name: Build
        run: >-
            docker buildx build ${{ github.workflow }} --pull --push
            --platform=linux/amd64
            --build-arg BUILD_VERSION
            --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            --label "org.opencontainers.image.version=${{ env.BUILD_VERSION }}"
            --label "org.opencontainers.image.revision=${{ github.sha }}"
            --tag docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            --tag docker.io/${{ env.REPOSITORY }}:latest
            --tag ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            --tag ghcr.io/${{ env.REPOSITORY }}:latest
