name: nginx-quic

on:
  push:
    branches: 
      - main
    paths:
      - nginx-quic/*
      - .github/workflows/nginx-quic.yml
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

env:
  BUILD_VERSION: "git"
  OPENSSL_VERSION: "3.0.0"
  PCRE_VERSION: "8.45"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }} 

jobs:

  deploy-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        quic: [boringssl,quictls]
    runs-on: ubuntu-20.04

    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0 
 
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }}
          labels: |
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=${{ env.REPOSITORY }}

      - name: GitHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: DockerHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      

      - name: Build and push (${{ matrix.quic }})
        uses: docker/build-push-action@v2.7.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ${{ github.workflow }}
          file: ${{ github.workflow }}/Dockerfile.ubuntu.${{ matrix.quic }}
          #platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          #platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le
          platforms: linux/amd64,linux/arm64
          #platforms: linux/amd64
          build-args: BUILD_VERSION
          cache-from: type=gha, scope=${{ github.workflow }}-${{ matrix.quic }}
          cache-to: type=gha, scope=${{ github.workflow }}-${{ matrix.quic }}, mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ matrix.quic }}
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ matrix.quic }}

  deploy-alpine:
    strategy:
      fail-fast: false
      matrix:
        quic: [boringssl,quictls]
    runs-on: ubuntu-20.04

    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0 
 
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }}
          labels: |
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=${{ env.REPOSITORY }}

      - name: GitHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: DockerHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      

      - name: Build and push (latest)
        if: ${{ matrix.quic == 'boringssl' }}
        uses: docker/build-push-action@v2.7.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ${{ github.workflow }}
          file: ${{ github.workflow }}/Dockerfile.alpine.${{ matrix.quic }}
          #platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          platforms: linux/amd64,linux/arm64
          #platforms: linux/amd64
          build-args: BUILD_VERSION
          cache-from: type=gha, scope=${{ github.workflow }}-${{ matrix.quic }}
          cache-to: type=gha, scope=${{ github.workflow }}-${{ matrix.quic }}, mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ matrix.quic }}
            docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ matrix.quic }}
            docker.io/${{ env.REPOSITORY }}:latest
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ matrix.quic }}
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ matrix.quic }}
            ghcr.io/${{ env.REPOSITORY }}:latest

      - name: Build and push (${{ matrix.quic }})
        if: ${{ matrix.quic != 'boringssl' }}
        uses: docker/build-push-action@v2.7.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ${{ github.workflow }}
          file: ${{ github.workflow }}/Dockerfile.alpine.${{ matrix.quic }}
          #platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          #platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le
          platforms: linux/amd64,linux/arm64
          #platforms: linux/amd64
          build-args: BUILD_VERSION
          cache-from: type=gha, scope=${{ github.workflow }}-${{ matrix.quic }}
          cache-to: type=gha, scope=${{ github.workflow }}-${{ matrix.quic }}, mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ matrix.quic }}
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ matrix.quic }}

