name: scan
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #image: [cloudflared]
        image: [age, ansible, bl3auto, cf-warp, cloudflared, coredns, dive, dnscontrol, dnscrypt-proxy, excalidraw, gobgp, headscale, lego, miller, nebula, nginx, nginx-distroless, onetun, pwru, spicedb, ssh-audit, sslyze, sync, tailscale, terraform, testssl.sh, youtube-dl, yt-dlp]
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.actor }}/${{ matrix.image }}:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-${{ matrix.image }}.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-${{ matrix.image }}.sarif'

