name: tailscale

on:
  push:
    branches: 
      - main
    paths:
      - tailscale/*
      - .github/workflows/tailscale.yml
  workflow_dispatch:

env:
  BUILD_VERSION: "1.2.10"
  BUILD_VERSION_LONG: "1.2.10-te480f8ddf"
  BUILD_VERSION_COMMIT: "e480f8ddf6f7334fda1b3d0dd1b500f2f01f961b"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }} 

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Source checkout
        uses: actions/checkout@v2 
 
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        
      - name: Set Docker metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.REPOSITORY }}
          label-custom: |
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            
      - name: GitHub login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ github.workflow }}
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          build-args: | 
            BUILD_VERSION
            BUILD_VERSION_LONG
            BUILD_VERSION_COMMIT
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            docker.io/${{ env.REPOSITORY }}:latest
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            ghcr.io/${{ env.REPOSITORY }}:latest
