# updatebot
#
# This runs every hour to check if upstream repos have had a new release
#
name: Update Python

on:
  push:
    branches: 
      - main
    paths:
      - scripts/updatePythonDeps.sh
      - .github/workflows/ansible.yml
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3"

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }} 

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  update-python:
    runs-on: ubuntu-20.04

    steps:
      # checkout with a PAT configured with workflow access to allow the workflow to check changes back in
      - name: Source checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0  
        with:
          token: ${{ secrets.UPDATE_SECRET }} 
          fetch-depth: 1
 
      - name: Add pipenv
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends pipenv python3.9
          
      - name: Update Python dependencies
        run: |
          scripts/updatePythonDeps.sh
